BITS 32

MULTIBOOT_MAGIC     equ 0x1BADB002
MULTIBOOT_ALIGN     equ 1 << 0
MULTIBOOT_MEM_INFO  equ 1 << 1
MULTIBOOT_FLAGS     equ MULTIBOOT_ALIGN | MULTIBOOT_MEM_INFO

section .multiboot
align 4
    dd MULTIBOOT_MAGIC
    dd MULTIBOOT_FLAGS
    dd -(MULTIBOOT_MAGIC + MULTIBOOT_FLAGS)
