[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
# This shouldn't be in here, but without it CLion doesn't resolve the cfg correctly
target = "targets/x86-unknown-z_os.json"
